dropdb studyhour -U postgres;
createdb studyhour -U postgres;
psql -d studyhour -f 1_comments_locations_users_tables.sql -U postgres;
psql -d studyhour -f 2_profile_location_image_tables.sql -U postgres;
psql -d studyhour -f 3_favorite_tables.sql -U postgres;
psql -d studyhour -f 4_add_long_lat_to_locationtable.sql -U postgres;
psql -d studyhour -f 5_add_booleans_to_comment.sql -U postgres;
psql -d studyhour -f 6_add_columns_to_users.sql -U postgres;
psql -d studyhour -f ../seeds/good_seed.sql -U postgres;
