insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('elliot','110','Elliot Vilhelm', 'San Diego', 'who am I', 'roger', 'I am team leader');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Rachel','110','Yoo Jin', 'Seoul', 'who am I', 'roger', 'I am Korean');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Roger','110','Cheng Cheng', 'Shanghai', 'who am I', 'roger', 'I am sad');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Xiaofan','110','Xiaofan Lin', 'Beijing', 'who am I', 'roger', 'I am smart');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('William','110','William Vuong', 'San Marcos', 'who am I', 'roger', 'I am outgoing');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Yusuf','110','Yusuf Khandoker', 'Los Angeles', 'who am I', 'roger', 'I am a cat');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Mher','110','Mher Arabian', 'Whole Foods', 'who am I', 'roger', 'I am not Arabian');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Adam','110','Adam Kabbara', 'Afghanistan', 'who am I', 'roger', 'I am lame');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Keny','110','Kenil Vora', 'Bombay', 'who am I', 'roger', 'I am here');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('Zixuan','110','Zixuan Zhang', 'Harbin', 'who am I', 'roger', 'I am quiet');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser1','banana','Banana Peel', 'San Diego', 'who am I', 'roger', 'I am not real');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser2','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser3','banana','Banana Peel', 'San Diego', 'who am I', 'roger', 'I am not real');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser4','banana','Banana Peel', 'San Diego', 'who am I', 'roger', 'I am not real');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser5','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser6','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser7','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser8','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');
insert into users(user_name, password, fullname, city, security_q, security_a, bio)values ('studyhouruser9','banana','Banana Pie','San Diego','who am I','roger','I am a tester too');


insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Starbucks','8750 Genesee Ave #244, San Diego, CA 92122','true','true','3','04:30:00','11:00:00','32.869668','-117.215512');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Philz Coffee','Shops at La Jolla Village, 8849 Villa La Jolla Dr #307, La Jolla, CA 92037','true','true','4','04:30:00','11:00:00','32.869356','-117.231973');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Whole Foods','8825 Villa La Jolla Dr, La Jolla, CA 92037','true','false','3','08:30:00','11:00:00','32.86874','-117.230626');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Living Room Cafe','1010 Prospect St, La Jolla, CA 92037','false','false','3','08:30:00','11:00:00','32.847712','-117.274822');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Clairemont Coffee','3095 Clairemont Dr, San Diego, CA 92117','false','false','3','08:30:00','11:00:00','32.797399','-117.192783');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Copa Vida','11055 Roselle St, San Diego, CA 92121','false','false','3','08:30:00','11:00:00','32.905022','-117.228892');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('Lestats on Park','4496 Park Blvd, San Diego, CA 92116','false','false','3','08:30:00','11:00:00','32.758937','-117.146394');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time, lat, lng)values ('The Forum Coffee House','4940, 4340 Genesee Ave #110, San Diego, CA 92117','true','false','3','08:30:00','11:00:00','32.83569','-117.19534');


insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','1','2','Great Atmosphere','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','1','3','Pretty crowded with nice people','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','1','4','Not lots of seats','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','1','4','Need more space, too many people','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('3','1','3','They have good food, but long waits','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('4','1','3','Great food and coffee!','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','1','3','I love this place, it is great!','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','1','3','Wow truly great for studying, came in on a sunday evening and they were very welcoming. I definetly will be back, say hi to patrick for me!','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','1','3','Been coming here since I was a kid, never gets old ...','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','1','4','Awesome atmosphere','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','1','4','Lots of students, very crowded','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','1','4','Awesome layouts, very comfortable','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','1','3','Horrible seats, very uncomfortable','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','1','2','Horrible study area','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','1','3','Very cold, uncomfortable','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','1','5','Highly recommended','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','1','1','Very hot, no air conditioning','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','1','3','No parking, would not recommend','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','1','3','Lots of space, nice atmosphere','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','1','2','Enjoyed my time here','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','1','5','Very loud, hard to study','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','1','4','Great atmosphere!','true', 'false');

insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','2','3','Awesome vibe, really enjoyed it.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','2','1','Cool atmosphere, great place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','2','2','Good seating!','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','2','4','Enjoyed studying here, cool vibes.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','2','4','Loved my time here, good studying.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','2','2','Loud but good atmosphere.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','2','4','Quiet atmosphere, cool place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','2','3','Cool place to study, recommended.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','2','1','A lot of study space, not bad.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','2','4','Enjoyed my time here, good studying.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','2','2','Didnt like this place, too loud.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','2','1','Terrible place, no places to sit.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','2','1','Not a lot of places to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','2','4','Good environmente.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','2','2','Not very comfortable to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','2','2','Not enough outlets.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','2','3','Good internet but no outlets.','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','2','2','Too loud, dont recommend.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','2','4','Really enjoyed my time studying here.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','2','3','Enjoyed my studying here.','true', 'true');

insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','7','3','Awesome vibe, really enjoyed it.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','7','1','Cool atmosphere, great place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','7','2','Good seating!','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','7','4','Enjoyed studying here, cool vibes.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','7','4','Loved my time here, good studying.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','7','2','Loud but good atmosphere.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','7','4','Quiet atmosphere, cool place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','7','3','Cool place to study, recommended.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','7','1','A lot of study space, not bad.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','7','4','Enjoyed my time here, good studying.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','7','2','Didnt like this place, too loud.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','7','1','Terrible place, no places to sit.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','7','1','Not a lot of places to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','7','4','Good environmente.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','7','2','Not very comfortable to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','7','2','Not enough outlets.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','7','3','Good internet but no outlets.','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','7','2','Too loud, dont recommend.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','7','4','Really enjoyed my time studying here.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','7','3','Enjoyed my studying here.','true', 'true');

insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','8','3','Awesome vibe, really enjoyed it.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','8','1','Cool atmosphere, great place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','8','2','Good seating!','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','8','4','Enjoyed studying here, cool vibes.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','8','4','Loved my time here, good studying.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','8','2','Loud but good atmosphere.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','8','4','Quiet atmosphere, cool place.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','8','3','Cool place to study, recommended.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','8','1','A lot of study space, not bad.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','8','4','Enjoyed my time here, good studying.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('1','8','2','Didnt like this place, too loud.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','8','1','Terrible place, no places to sit.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','8','1','Not a lot of places to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','8','4','Good environmente.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','8','2','Not very comfortable to study.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','8','2','Not enough outlets.','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','8','3','Good internet but no outlets.','false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','8','2','Too loud, dont recommend.','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','8','4','Really enjoyed my time studying here.','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('10','8','3','Enjoyed my studying here.','true', 'true');

insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','5','1', 'Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','5','2', 'Too loud. Do not recommend', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('3','5','3', 'Good environment', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('4','5','4', 'Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','5','5', 'Awesome atmosphere', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','5','1', 'A cafeteria would make the location better for long hours', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','5','2', 'Too loud. Do not recommend', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','5','3', 'Awesome atmosphere', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','5','4', 'Good environment', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','5','5', 'Not very comfortable to study', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','5','1',' Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','5','2', 'Too loud. Do not recommend', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('3','5','3', 'Good environment', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('4','5','4', 'Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','5','5', 'Awesome atmosphere', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','5','1', 'A cafeteria would make the location better for long hours', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','5','2', 'Too loud. Do not recommend', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','5','3', 'Awesome atmosphere', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','5','4', 'Good environment', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','5','5', 'Not very comfortable to study', 'false', 'true');

insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','6','1',' Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','6','2', 'Too loud. Do not recommend', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('3','6','3', 'Good environment', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('4','6','4', 'Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','6','5', 'Awesome atmosphere', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','6','1', 'A cafeteria would make the location better for long hours', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','6','2', 'Too loud. Do not recommend', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','6','3', 'Awesome atmosphere', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','6','4', 'Good environment', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','6','5', 'Not very comfortable to study', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','6','1',' Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('2','6','2', 'Too loud. Do not recommend', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('3','6','3', 'Good environment', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('4','6','4', 'Not very comfortable to study', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('5','6','5', 'Awesome atmosphere', 'true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('6','6','1', 'A cafeteria would make the location better for long hours', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('7','6','2', 'Too loud. Do not recommend', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('8','6','3', 'Awesome atmosphere', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('9','6','4', 'Good environment', 'false', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet)values ('10','6','5', 'Not very comfortable to study', 'false', 'true');

insert into comments(user_id, location_id, rating, text, outlet, internet)values ('1','3','2', 'would not recommend weak coffee game','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('2','3','4','great place to read a book','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('3','3','5','The barista was a 10/10, as an extra it was quite and comfortable to study','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('4','3','3','The employee was eyeing me because I stayed sitting for 10 hours after buying the cheapest thing on the menu','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('5','3','4','very comfortable place to take a sip of tea','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('6','3','4','great place','true', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('7','3','3','big table for teammeatings','true', 'true');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('8','3','2','smelly place, I would not recomment this place','false', 'false');
insert into comments(user_id, location_id, rating, text, outlet, internet) values ('9','3','4','great coffee, comfy and quite','true', 'true');

