insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Geisel 8th floor','9500 Gilman dr, San Diego','true','true','1', '7:30am', '12:00am');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Geisel 7th floor','9500 Gilman dr, San Diego','true','true','1', '7:30am', '12:00am');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Geisel 6th floor','9500 Gilman dr, San Diego','true','true','3', '7:30am', '12:00am');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Geisel 2nd floor','9500 Gilman dr, San Diego','true','true','8', '12:00am', '11:59pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Geisel 1st floor','9500 Gilman dr, San Diego','true','true','8', '7:30am', '12:00am');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Starbucks','4150 Regents Park Row, La Jolla','true','tree','5', '5:00am', '8:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Home sweet home','8950 Costa Verde Blvd #3208, San Diego','true','true', '2', '10:00am', '3:00am');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Starbucks','8750 Genesee Ave #244, San Diego','true','true', '7', '4:30am', '11:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('MNGO cafe','4176 Convoy St, San Diego','false','false', '7', '12:00pm', '11:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Biomedical Library','9500 Gilman dr, San Diego','true','true', '3', '8:00am', '6:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('The Forum Coffee House','4340 Genesee Ave, Ste 110, San Diego','true','true', '5', '6:00am', '7:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Moniker General- Coffee','2860 Sims Rd, San Diego','false','true', '5', '7:00am', '7:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Copa Vida','11055 Roselle St Ste 105, San Diego','fasle','true','4', '7:00am', '7:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Gotcha Tea','5375 Kearny Villa Rd, ste 113, San Diego','false','true','1', '11:00am', '11:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Living Room Coffeehouse','5900 El Cajon Blvd, San Diego','false','false','5', '8:30am', '1:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Duet Coffee','6526 El Cajon Blvd, San Diego','false','true','5', '7:00am', '5:00pm');
insert into locations(name, address, outlet, internet, noise_level, open_time, close_time) values ('Dungeon(EBU3B B1)','9500 Gilman Dr, San Diego','true','true','4', '12:00am', '11:59pm');
insert into users(user_name, password) values ('Roger','fml');
insert into users(user_name, password) values ('Sam','ahhhhhh');
insert into users(user_name, password) values ('Elliot','fuuuuuk');
insert into users(user_name, password) values ('rachel','lovely');
insert into users(user_name, password) values ('john','123');
insert into users(user_name, password) values ('adam','123');
insert into users(user_name, password) values ('mher','mhm?');
insert into users(user_name, password) values ('william','agh');
insert into users(user_name, password) values ('keny','heh');
insert into users(user_name, password) values ('yusuf','huh');
insert into comments(user_id, location_id, rating, text) values ('1','1','2','Too Quite');
insert into comments(user_id, location_id, rating, text) values ('2','1','1','It is always packed. No place to sit.');
insert into comments(user_id, location_id, rating, text) values ('3','1','4','It is okay.');
insert into comments(user_id, location_id, rating, text) values ('4','1','5','I love this place. It is so quite.');
insert into comments(user_id, location_id, rating, text) values ('5','1','3','I hate this school');
insert into comments(user_id, location_id, rating, text) values ('1','2','3','I dunno');
insert into comments(user_id, location_id, rating, text) values ('2','2','4','why do you study at school');
insert into comments(user_id, location_id, rating, text) values ('3','2','4','I donnot need to study');
insert into comments(user_id, location_id, rating, text) values ('4','2','3','too smart to study');
insert into comments(user_id, location_id, rating, text) values ('5','2','3','geisel is so depressing');
insert into comments(user_id, location_id, rating, text) values ('1','6','1','it sucks here.');
insert into comments(user_id, location_id, rating, text) values ('2','6','1','nasty.');
insert into comments(user_id, location_id, rating, text) values ('3','6','1','EW');
insert into comments(user_id, location_id, rating, text) values ('4','6','1','adlkfja;l');
insert into comments(user_id, location_id, rating, text) values ('5','7','1','this is a coffe shop, there are no internent.');
insert into comments(user_id, location_id, rating, text) values ('3','2','3','it has everything.');
insert into comments(user_id, location_id, rating, text) values ('1','8','2','Too Quite');
insert into comments(user_id, location_id, rating, text) values ('2','8','1','It is always packed. No place to sit.');
insert into comments(user_id, location_id, rating, text) values ('3','8','4','It is okay.');
insert into comments(user_id, location_id, rating, text) values ('4','9','5','I love this place. It is so quite.');
insert into comments(user_id, location_id, rating, text) values ('5','9','3','I hate this school');
insert into comments(user_id, location_id, rating, text) values ('1','9','2','Too Quite');
insert into comments(user_id, location_id, rating, text) values ('2','9','1','It is always packed. No place to sit.');
insert into comments(user_id, location_id, rating, text) values ('3','6','4','It is okay.');
insert into comments(user_id, location_id, rating, text) values ('4','6','5','I love this place. It is so quite.');
insert into comments(user_id, location_id, rating, text) values ('5','6','3','I hate this school');
insert into comments(user_id, location_id, rating, text) values ('1','6','2','Too Quite');
insert into comments(user_id, location_id, rating, text) values ('2','6','1','It is always packed. No place to sit.');
insert into comments(user_id, location_id, rating, text) values ('3','5','4','It is okay.');
insert into comments(user_id, location_id, rating, text) values ('4','5','5','I love this place. It is so quite.');
insert into comments(user_id, location_id, rating, text) values ('5','5','3','I hate this school');
insert into comments(user_id, location_id, rating, text) values ('1','1','1','Go, go, go, go go, go, go, sha');
insert into comments(user_id, location_id, rating, text) values ('2','2','2','wty Its your birthday We gon');
insert into comments(user_id, location_id, rating, text) values ('3','3','3',' party like its yo birthday W');
insert into comments(user_id, location_id, rating, text) values ('4','4','4','e gon sip Bacardi like its y');
insert into comments(user_id, location_id, rating, text) values ('5','5','1','our birthday And you know we d');
insert into comments(user_id, location_id, rating, text) values ('6','6','2','ont give a fuck Its not your');
insert into comments(user_id, location_id, rating, text) values ('7','7','3',' birthday! You can find me in ');
insert into comments(user_id, location_id, rating, text) values ('8','8','4','the club, bottle full of bub L');
insert into comments(user_id, location_id, rating, text) values ('9','9','1','ook mami I got the X if you in');
insert into comments(user_id, location_id, rating, text) values ('1','10','2','to taking drugs Im into havin');
insert into comments(user_id, location_id, rating, text) values ('2','11','3','g sex, I aint into making lov');
insert into comments(user_id, location_id, rating, text) values ('3','12','4','e So come give me a hug if you');
insert into comments(user_id, location_id, rating, text) values ('4','13','1',' into to getting rubbedYou can');
insert into comments(user_id, location_id, rating, text) values ('5','14','2',' find me in the club, bottle f');
insert into comments(user_id, location_id, rating, text) values ('6','15','3','ull of but Look mami I got the');
insert into comments(user_id, location_id, rating, text) values ('7','16','4',' X if you into taking drugsIm');
insert into comments(user_id, location_id, rating, text) values ('8','1','1',' into having sex, I aint into');
insert into comments(user_id, location_id, rating, text) values ('9','2','2',' making love So come give me a');
insert into comments(user_id, location_id, rating, text) values ('1','3','3',' hug if you into to getting ru');
insert into comments(user_id, location_id, rating, text) values ('2','4','4','bbed When I pull out up front,');
insert into comments(user_id, location_id, rating, text) values ('3','5','1',' you see the Benz on dubs When');
insert into comments(user_id, location_id, rating, text) values ('4','6','2',' I roll twenty deep, its twen');
insert into comments(user_id, location_id, rating, text) values ('5','7','3','ty knives in the clubNiggas he');
insert into comments(user_id, location_id, rating, text) values ('6','8','4','ard I fuck with Dre, now they ');
insert into comments(user_id, location_id, rating, text) values ('7','9','1','want to show me love When you ');
insert into comments(user_id, location_id, rating, text) values ('8','10','2','sell like Eminem, and the hoes');
insert into comments(user_id, location_id, rating, text) values ('9','11','3',' they want to fuckBut homie ai');
insert into comments(user_id, location_id, rating, text) values ('1','12','4','nt nothing change hold down, ');
insert into comments(user_id, location_id, rating, text) values ('2','13','1','Gs up I see Xzibit in the Cut');
insert into comments(user_id, location_id, rating, text) values ('3','14','2','t that nigga roll that weed up');
insert into comments(user_id, location_id, rating, text) values ('4','15','3',' If you watch how I move youl');
insert into comments(user_id, location_id, rating, text) values ('5','16','4','l mistake me for a player or p');
insert into comments(user_id, location_id, rating, text) values ('6','1','1','imp Been hit wit a few shells ');
insert into comments(user_id, location_id, rating, text) values ('7','2','2','but I dont walk wit a limp In');
insert into comments(user_id, location_id, rating, text) values ('8','3','3',' the hood then the ladies sayi');
insert into comments(user_id, location_id, rating, text) values ('9','4','4','ng 50 you hot They like me, I ');
insert into comments(user_id, location_id, rating, text) values ('1','5','1','want them to love me like they');
insert into comments(user_id, location_id, rating, text) values ('2','6','2',' love PacBut holla in New Yor');
insert into comments(user_id, location_id, rating, text) values ('3','7','3','k them nigga ll tell ya Im l');
insert into comments(user_id, location_id, rating, text) values ('4','8','4','oco And the plan is to put the');
insert into comments(user_id, location_id, rating, text) values ('5','9','1',' rap game in a choke hold Im ');
insert into comments(user_id, location_id, rating, text) values ('6','10','2','feelin focused man, my money ');
insert into comments(user_id, location_id, rating, text) values ('7','11','3','on my mindI got a mill out the');
insert into comments(user_id, location_id, rating, text) values ('8','12','4',' deal and Im still on the gri');
insert into comments(user_id, location_id, rating, text) values ('9','13','1','nd Now shawty said she feeling');
insert into comments(user_id, location_id, rating, text) values ('1','14','2',' my style, she feeling my flow');
insert into comments(user_id, location_id, rating, text) values ('2','15','3','Her girlfriend want to get bi ');
insert into comments(user_id, location_id, rating, text) values ('3','16','4','and they ready to go You can f');
insert into comments(user_id, location_id, rating, text) values ('4','1','1','ind me in the club, bottle ful');
insert into comments(user_id, location_id, rating, text) values ('5','2','2','l of bub Look mami I got the X');
insert into comments(user_id, location_id, rating, text) values ('6','3','3',' if you into taking drugs Im ');
insert into comments(user_id, location_id, rating, text) values ('7','4','4','into having sex, I ait into ');
insert into comments(user_id, location_id, rating, text) values ('8','5','1','making love So come give me a ');
insert into comments(user_id, location_id, rating, text) values ('9','6','2','hug if you into to getting rub');
insert into comments(user_id, location_id, rating, text) values ('1','7','3','bedYou can find me in the club');
insert into comments(user_id, location_id, rating, text) values ('2','8','4',', bottle full of bub Look mami');
insert into comments(user_id, location_id, rating, text) values ('3','9','1',' I got the X if you into takin');
insert into comments(user_id, location_id, rating, text) values ('4','10','2','g drugsIm into having sex, I ');
insert into comments(user_id, location_id, rating, text) values ('5','11','3','aint into making loveSo come ');
insert into comments(user_id, location_id, rating, text) values ('6','12','4','give me a hug if you into to g');
insert into comments(user_id, location_id, rating, text) values ('7','13','1','etting rubbedMy flow, my show ');
insert into comments(user_id, location_id, rating, text) values ('8','14','2','brought me the dough That boug');
insert into comments(user_id, location_id, rating, text) values ('9','15','3','ht me all my fancy things My c');
insert into comments(user_id, location_id, rating, text) values ('1','16','4','rib, my cars, my pools, my jew');
insert into comments(user_id, location_id, rating, text) values ('2','1','1','els Look, nigga, I came up and');
insert into comments(user_id, location_id, rating, text) values ('3','2','2',' I aint changed And you shoul');
insert into comments(user_id, location_id, rating, text) values ('4','3','3','d love it, way more then you h');
insert into comments(user_id, location_id, rating, text) values ('5','4','4','ate it Nigga you mad? I though');
insert into comments(user_id, location_id, rating, text) values ('6','5','1','t that youd be happy I made i');
insert into comments(user_id, location_id, rating, text) values ('7','6','2','t Im that cat by the bar toas');
insert into comments(user_id, location_id, rating, text) values ('8','7','3','ting to the good life You that');
insert into comments(user_id, location_id, rating, text) values ('9','8','4',' fagot ass nigga trying to pul');
insert into comments(user_id, location_id, rating, text) values ('1','9','1','l me back right? When my junk ');
insert into comments(user_id, location_id, rating, text) values ('2','10','2','get to pumping in the club it');
insert into comments(user_id, location_id, rating, text) values ('3','11','3','s on I wink my eye at ya bitch');
insert into comments(user_id, location_id, rating, text) values ('4','12','4',', if she smiles she gone If th');
insert into comments(user_id, location_id, rating, text) values ('5','13','1','e roof on fire, let the mother');
insert into comments(user_id, location_id, rating, text) values ('6','14','2','fucker burn If you talking bou');
insert into comments(user_id, location_id, rating, text) values ('7','15','3','t money homie, I aint concern');
insert into comments(user_id, location_id, rating, text) values ('8','16','4','ed Im a tell you what Banks t');
insert into comments(user_id, location_id, rating, text) values ('9','1','1','old me cause go head switch th');
insert into comments(user_id, location_id, rating, text) values ('1','2','2','e style up If the niggas hate ');
insert into comments(user_id, location_id, rating, text) values ('2','3','3','then let em hateWatch the mon');
insert into comments(user_id, location_id, rating, text) values ('3','4','4','ey pile upOr we go upside ther');
insert into comments(user_id, location_id, rating, text) values ('4','5','1','e wit a bottle of bub You know');
insert into comments(user_id, location_id, rating, text) values ('5','6','2',' where we fucking be You can f');
insert into comments(user_id, location_id, rating, text) values ('6','7','3','ind me in the club, bottle ful');
insert into comments(user_id, location_id, rating, text) values ('7','8','4','l of bubLook mami I got the X ');
insert into comments(user_id, location_id, rating, text) values ('8','9','1','if you into taking drugs Im i');
insert into comments(user_id, location_id, rating, text) values ('9','10','2','nto having sex, I aint into m');
insert into comments(user_id, location_id, rating, text) values ('1','11','3','aking love So come give me a h');
insert into comments(user_id, location_id, rating, text) values ('2','12','4','ug if you into to getting rubb');
insert into comments(user_id, location_id, rating, text) values ('3','13','1','ed');

