insert into locations(name, address, outlet, internet, noise_level) values ('Geisel','San diego','false','true','4');
insert into locations(name, address, outlet, internet, noise_level) values ('Starbucks','San diego','true','false','7');
insert into locations(name, address, outlet, internet, noise_level) values ('Home','Miami','true','true', '2');
insert into users(user_name, password) values ('Roger','fml');
insert into users(user_name, password) values ('Sam','ahhhhhh');
insert into users(user_name, password) values ('Elliot','fuuuuuk');
insert into users(user_name, password) values ('rachel','lovely');
insert into comments(user_id, location_id, rating, text) values ('1','3','1','this is a school library, there are no sockets.');
insert into comments(user_id, location_id, rating, text) values ('2','1','2','this is a coffe shop, there are no internent.');
insert into comments(user_id, location_id, rating, text) values ('3','2','3','this is my home, it has everything.');
